Add zsh-zoxide
z-shell/wiki pull request #59
Opened 2022-08-03 21:16 UTC by 0xMRTT

2022-08-03 21:41 UTC, ss-o requested changes
Many errors, build and check + punctuation. Also need more detailed info.

2022-08-03 22:08 UTC, ss-o requested changes
- In markdown (for rendering) don't use a newline.
- Include some copy-paste examples (as I showed you zi-crasis) so the reader can test/see results.
  - Use as examples of +zi-message which are used in zi / annexes as there are many use-case scenarios.
- Asciinema or similar preview to support examples is preferred but not required.

2022-08-03 22:08 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +| `st`      | <Image img={require('@site/static/img/png/zi-messages/st.png')} />      |
The table is nice.

2022-08-03 22:10 UTC, 0xMRTT commented on docs/guides/syntax/20_zi_messages.md
> +| `st`      | <Image img={require('@site/static/img/png/zi-messages/st.png')} />      |
Thanks, need to add the rest

2022-08-03 22:42 UTC, ss-o commented
+zi-message {auto} https://github.com/ss-o/zi/blob/tmp/zi.zsh#L1652-L1657

```zsh
+zi-message "{auto}zi"
+zi-message "{auto}git"
+zi-message "{auto}https://wiki.zshell.dev ftp://zshell.dev rsync://zshell.dev ssh://github.com scp://zshell.dev ntp://time.cloudflare.com file://local.html"
+zi-message "{auto}z-shell/zi 0xMRTT/dotfiles"
+zi-message "{auto}10000000000s"
+zi-message "{auto}1000 66 000"
+zi-message "{auto}zi analytics"
+zi-message "{auto}sbin'a -> b'"
+zi-message "{auto} \`z-shell Zi'"
+zi-message "{auto} 'z-shell Zi'"
+zi-message "{auto} \"z-shell Zi\""
```

![img](https://user-images.githubusercontent.com/59910950/182724755-c4bf53a7-1748-46e1-9054-8b9788dd1e51.gif)

If you want to test this messages install: ss-o/zi branch: tmp

2022-08-06 04:07 UTC, ss-o requested changes

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +## Modifiers list
It's not modifiers + plus can be confused with ice modifiers.

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +title: "🔀 Zi messages"
```suggestion
title: "💬 Zi messages"
```

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +| Modifier | Output                                                            | Modifier | Output                                                            | Modifier | Output
Some table improvements? :see_no_evil:

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +## Modifiers list
If you struggle to find correct terms in English, Grammarly does that pretty well, also can be integrated into vscode, etc.

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> ++zi-message "{annex}default-ice-annex{ehi}:{rst}{msg} Missing any" "ices. Usage{ehi}:{rst}{nl}"
```suggestion
+zi-message "{annex}default-ice-annex{ehi}:{rst} {msg}Missing any ices. Usage{ehi}:{rst}{nl}"
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +> Wiki: [automatic, condition based (loading/unloading)](https://wiki.zshell.dev/docs/getting_started/overview#automatic-condition-based---load--unload)
```suggestion
> Wiki: [automatic, condition based (loading/unloading)](/docs/getting_started/overview#automatic-condition-based---load--unload)
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +- [x] Completions auto-loaded: [commands](https://wiki.zshell.dev/docs/guides/commands#completions-management), [ice-modifiers](https://wiki.zshell.dev/docs/guides/syntax/ice-modifiers#completions)
```suggestion
- [x] Completions auto-loaded: [commands](/docs/guides/commands#completions-management), [ice-modifiers](/docs/guides/syntax/ice-modifiers#completions)
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +[fzf](https://github.com/junegunn/fzf) is a command-line fuzzy finder, used by zoxide for interactive selection. It can be installed from [here](https://github.com/z-shell/fzf) as a zi package.
```suggestion
[fzf](https://github.com/junegunn/fzf) is a command-line fuzzy finder, used by zoxide for interactive selection. It can be installed as a Zi [package](/ecosystem/packages/available-packages#the-fzf-command-line-fuzzy-finder).
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```zsh
```suggestion
```shell showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```zsh
```suggestion
```shell showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```zsh
```suggestion
```shell showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```zsh
```suggestion
```shell showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +before the installation of zoxide
```suggestion
If you want to replace `cd` with `zoxide`. You can set the prefix to `cd` by setting `_ZO_CMD_PREFIX=cd` in `~.zshrc` before the installation of zoxide
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +- [x] Manpages auto installed: [\$ZI[MAN_DIR]](https://wiki.zshell.dev/docs/guides/customization#customizing-paths)
```suggestion
- [x] Manpages auto installed: [\$ZI[MAN_DIR]](/docs/guides/customization#customizing-paths)
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +### Install `zoxide`
```suggestion
## Install `zoxide`
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +### Install `zsh-zoxide`
```suggestion
## Install `zsh-zoxide`
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### Standart syntax
```suggestion
### Standart syntax
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### The "For" syntax
```suggestion
### The "For" syntax
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### Turbo mode + "For" syntax
```suggestion
### Turbo mode + "For" syntax
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +### Environment variables and usage with other plugin managers
```suggestion
## Environment variables and usage with other plugin managers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +### Import your data
```suggestion
## Import your data
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### autojump
```suggestion
### autojump
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### z, z.lua or zsh-z
```suggestion
### z, z.lua or zsh-z
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +### Environment variables and usage with Zi
```suggestion
## Environment variables and usage with Zi
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +#### Change prefix
```suggestion
### Change prefix
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```sh
```suggestion
```sh showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +```sh
```suggestion
```sh showLineNumbers
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +It remembers which directories you use most frequently, so you can "jump" to them in just a few keystrokes.
```suggestion
It remembers which directories you use most frequently, so you can "jump" to them in just a few keystrokes.
```

2022-08-06 04:07 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +image: img/logo/320x320.png
```suggestion
image: /img/logo/320x320.png
```

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +description: Use `+zi-message` for rich text output
```suggestion
description: Zi's messages for rich text output
```

2022-08-06 04:07 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +<Image img={require('@site/static/img/png/+zi-message.png')} />
Please don't put this image, you need to make it clean, this one I made for you to show has incorrect lines.

2022-08-06 04:15 UTC, ss-o commented on ecosystem/plugins/zsh_zoxide.md
> +<TabItem value="zi" label="WIth Zi" default>
```suggestion
<TabItem value="zi" label="With Zi" default>
```

2022-08-06 09:53 UTC, 0xMRTT commented
Think that now it's done

2022-08-06 14:33 UTC, ss-o commented on docs/guides/syntax/20_zi_messages.md
> +color, blink, underline, italic, etc... `+zi-message` is used in Zi for each output. Like this:
```suggestion
You can use `+zi-message` for printing rich text messages. `+zi-message` support output like URL, color, blink, underline, italic, etc... `+zi-message` is used in Zi for each output. Like this:
```

2022-08-06 15:57 UTC, ss-o requested changes
## Remove:

- static/asciicast/gif/zi_messages.gif
- static/img/png/+zi-message.png

It has mistakes.

## Add explanations so it makes sense.

```shell
+zi-message "{auto}zi"
+zi-message "{auto}git"
+zi-message "{auto}https://wiki.zshell.dev ftp://zshell.dev rsync://zshell.dev ssh://github.com scp://zshell.dev ntp://time.cloudflare.com file://local.html"
+zi-message "{auto}z-shell/zi 0xMRTT/dotfiles"
+zi-message "{auto}10000000000s"
+zi-message "{auto}1000 66 000"
+zi-message "{auto}zi analytics"
+zi-message "{auto}sbin'a -> b'"
+zi-message "{auto} \`z-shell Zi'"
+zi-message "{auto} 'z-shell Zi'"
+zi-message "{auto} \"z-shell Zi\""
```

Reduce duplicate / not required links, e.g:

```md
## Add interactive selection with [`fzf`](https://github.com/z-shell/fzf)

[fzf](https://github.com/junegunn/fzf)
```

> both have the same title and different links - it kills wiki performance, search, everything...

## Reduce words

Too many words, and duplicates, need to be removed, also fix all links to be organized the same as all other pages. This is very bad:

```md
Follow [https://github.com/ajeetdsouza/zoxide#step-1-install-zoxide](https://github.com/ajeetdsouza/zoxide#step-1-install-zoxide)
```

And many more issues double-check to be the same formating as all pages. Now will be 2 pages different from all others.

If you don't want or are struggling let me know all do all myself. As it takes much more time to check on everychange.

2022-08-06 16:30 UTC, 0xMRTT commented
I think that you can end because it will take too much time. I'll learn from your commits. Because I'm not good at writing 😉. So, I'll learn from your commits and retry later

2022-08-06 16:39 UTC, ss-o commented
Ok, leave it as is now, I'll finish :+1: I assume the problem is you need to get more familiar with how other apps uses docs, as it looks good rendered, but for SEO, crowdin, algolia it is very bad, so I think after some time you will be alright :octocat:

2023-04-01 05:29 UTC, closed without merging